/**
 * My API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CreateScenarioCourseGroup } from './createScenarioCourseGroup';


export interface CreateScenarioCourse { 
    courseId: number;
    groups?: Array<CreateScenarioCourseGroup>;
}

