/**
 * My API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PaginationMeta } from './paginationMeta';
import { Scenario } from './scenario';


export interface PaginatedScenarioResponse { 
    data: Array<Scenario>;
    meta: PaginationMeta;
}

