/**
 * My API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ScenarioCourseGroupTeacherAssignment } from './scenarioCourseGroupTeacherAssignment';


export interface ScenarioCourseGroup { 
    id: number;
    groupName: string;
    teacherAssignments?: Array<ScenarioCourseGroupTeacherAssignment>;
}

