/**
 * My API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Teacher } from './teacher';
import { Subject } from './subject';


export interface ScenarioCourseGroupTeacherAssignment { 
    teacher: Teacher;
    subject: Subject;
}

