/**
 * My API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ScenarioCourse } from './scenarioCourse';


export interface Scenario { 
    id: number;
    name: string;
    courses?: Array<ScenarioCourse>;
    status?: ScenarioStatusEnum;
}
export enum ScenarioStatusEnum {
    SolutionPending = 'SOLUTION_PENDING',
    SolutionReady = 'SOLUTION_READY',
    Published = 'PUBLISHED'
};



