/**
 * My API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TimetableDayEntry } from './timetableDayEntry';


export interface Timetable { 
    courseId?: number;
    groupId?: number;
    hours: Array<Array<TimetableDayEntry>>;
}

