/**
 * My API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CreateScenarioCourse } from './createScenarioCourse';


export interface UpdateScenarioDto { 
    name?: string;
    courses?: Array<CreateScenarioCourse>;
}

