/**
 * My API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PaginationMeta } from './paginationMeta';
import { Course } from './course';


export interface PaginatedCourseResponse { 
    data: Array<Course>;
    meta: PaginationMeta;
}

