/**
 * My API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SubjectDto } from './subjectDto';
import { Workload } from './workload';


export interface SubjectWorkLoad { 
    subject?: SubjectDto;
    workload?: Workload;
}

