/**
 * My API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SubjectCoursesInner } from './subjectCoursesInner';


export interface Subject { 
    id: number;
    name: string;
    courses?: Array<SubjectCoursesInner>;
}

