/**
 * My API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SubjectDto } from './subjectDto';


export interface Habilitation { 
    id: number;
    name: string;
    course?: number;
    subjects?: Array<SubjectDto>;
}

