/**
 * My API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PaginationMeta } from './paginationMeta';
import { Teacher } from './teacher';


export interface PaginatedTeacherResponse { 
    data: Array<Teacher>;
    meta: PaginationMeta;
}

