/**
 * My API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Habilitation } from './habilitation';


export interface UpdateTeacherDto { 
    name?: string;
    habilitations?: Array<Habilitation>;
}

