import { generateFiles, readJson, Tree, writeJson } from "@nx/devkit";
import { EntityGeneratorSchema } from "../schema";
import path = require("path");
import { flushChanges } from "nx/src/generators/tree";
import { execSync } from "child_process";

export function generateYamlFile(tree: Tree, options: EntityGeneratorSchema) {
    console.log('Generating yaml file...')
  generateFiles(tree, 
    path.join(
      `${__dirname}`, 
      '../files/api'), 
      'apps/backend/api', {
        entity: options.name,
        entityPlural: options.name + 's',
        entityClassName: options.name.charAt(0).toUpperCase() + options.name.slice(1),
        tpl: ''
      });
  console.log('Yaml file generated successfully');
  
  console.log('Updating package.json to include generation sript...');
  const packageJson = readJson(tree,'package.json')
  packageJson.scripts[`generate:${options.name}`] = `openapi-generator-cli generate -g typescript-nestjs-server -i apps/backend/api/${options.name}.yaml -o libs/backend/generated-server-${options.name}/src --additional-properties=supportsES6=true`
  writeJson(tree, 'package.json', packageJson);
  console.log('package.json updated successfully');
  
  console.log('Flushing changes to disk...');
  flushChanges(tree.root, tree.listChanges());
  console.log('Changes flushed');
  console.log('Generating autogenerated stuff...')
  execSync(`openapi-generator-cli generate -g typescript-nestjs-server -i apps/backend/api/${options.name}.yaml -o libs/backend/generated-server-${options.name}/src --additional-properties=supportsES6=true`, {
    stdio: 'inherit',
  });
  console.log('Autogenerated stuff generated successfully');
}